name: ci
on:
  pull_request:
  push:
    branches:
      - macos
jobs:
  format:
    name: cargo fmt
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run fmt
        run: make fmt

  cargo-clippy:
    name: cargo clippy
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5

       # This action will configure Rust cache automatically:
       # https://github.com/actions-rust-lang/setup-rust-toolchain?tab=readme-ov-file#inputs
      - name: Setup toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - run: make lint

  build-and-test:
    name: build and test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build
        run: make build
      
      - name: Build with metal
        run: cargo build --features metal

#      - name: Run Unit Test
#        run: make test